name: hug_mun
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-78.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  collection: '^1.17.0'
  dio: '^5.2.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  fluent_assertions: ^0.4.0
  given_when_then_unit_test: ^0.2.1
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  built_value_generator: '>=8.4.0 <9.0.0'
  test: ^1.16.0
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - images/raven.jpg
