// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfufKzDRwGK7c1c7rXkrIemGw-3ZAkP14',
    appId: '1:340233529876:web:27ecaedfd2dbdc873d5501',
    messagingSenderId: '340233529876',
    projectId: 'hugmun-f14e3',
    authDomain: 'hugmun-f14e3.firebaseapp.com',
    storageBucket: 'hugmun-f14e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9miP2HsqsuzRw3-nYPLeptm4LO2o5Kuk',
    appId: '1:340233529876:android:5a79bd44d01fea4c3d5501',
    messagingSenderId: '340233529876',
    projectId: 'hugmun-f14e3',
    storageBucket: 'hugmun-f14e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjvQqXZbT3PBM0o_gxWmMDujJViZpYsfI',
    appId: '1:340233529876:ios:7573dcb8578abb2c3d5501',
    messagingSenderId: '340233529876',
    projectId: 'hugmun-f14e3',
    storageBucket: 'hugmun-f14e3.appspot.com',
    iosBundleId: 'com.example.hugMun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjvQqXZbT3PBM0o_gxWmMDujJViZpYsfI',
    appId: '1:340233529876:ios:1e8df264223573da3d5501',
    messagingSenderId: '340233529876',
    projectId: 'hugmun-f14e3',
    storageBucket: 'hugmun-f14e3.appspot.com',
    iosBundleId: 'com.example.hugMun.RunnerTests',
  );
}
