///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesRaven = 'images/raven.jpg';
  static const String imagesCrow = 'images/crow.png';
}
